### ISSUE TITLE
[需要帮助]关于打包编码问题

### ISSUE THREAD

**Issue by gggssepgf** [ZQF-ReVN/RxPJADV#2]
大佬您好，我个人是个小白，逆向相关的是一点不懂，我用您提供的工具把scenario_msg.json和scenario_msg.json已经提取出来并且汉化好了，但是在打包回去的时候报错
RxCvt::ToMBCS Error!
请问是因为不支持中文字符吗，我使用936和932都不行，65001打包成功了但是游戏文字是乱码，有什么解决办法吗

**Comment by Dir-A** [comment]
https://github.com/Dir-A/CMVS_Tools/issues/5#issuecomment-1968759657

**Comment by gggssepgf** [comment]
> [Dir-A/CMVS_Tools#5 (comment)](https://github.com/Dir-A/CMVS_Tools/issues/5#issuecomment-1968759657)

但是我用936也是报错，是因为我翻译后的文本里有gbk不支持的字符么

**Comment by Dir-A** [comment]
试试不就知道了

**Comment by gggssepgf** [comment]
> 试试不就知道了
我把gbk不支持的字符替换掉了，现在已经能正常封包回去了，不过遇到了和那个issue一样的问题，文字显示是乱码，请问下大佬这是必须得自己修改游戏解决么

**Comment by Dir-A** [comment]
https://github.com/Dir-A/Dir-A_Essays_MD/blob/main/Reverse%2F%5BPJADV%5D%20%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%E5%88%86%E6%9E%90%2F%5BPJADV%5D%20%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%E5%88%86%E6%9E%90.md#%E5%AE%9E%E4%BE%8B%E4%BF%AE%E6%94%B9

**Comment by gggssepgf** [comment]
> https://github.com/Dir-A/Dir-A_Essays_MD/blob/main/Reverse%2F%5BPJADV%5D%20%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%E5%88%86%E6%9E%90%2F%5BPJADV%5D%20%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%E5%88%86%E6%9E%90.md#%E5%AE%9E%E4%BE%8B%E4%BF%AE%E6%94%B9
谢谢大佬，不过我小白一个，没学过逆向相关的东西，只能看出来这游戏应该是调用的系统api渲染，因为文件里没有fontdata这些文件
尝试用x64dbg搜索了一下CreateFontIndirectA，但是因为实在是不懂汇编，看不出来这函数是咋调用的，大佬可以指导一下么
![image](https://github.com/Dir-A/PJADV_Tools/assets/48855391/0dbfd6f7-a1d3-486f-bcfd-85c353c10044)
![image](https://github.com/Dir-A/PJADV_Tools/assets/48855391/f3e039da-e417-4318-aa60-e9ee5f4b138b)

**Comment by gggssepgf** [comment]
感谢大佬的工具和帮助，因为我实在不会逆向，最后用gbk to jis加上uif加载定制字体解决了简体显示的问题，麻烦大佬了

**Comment by prowaynes** [comment]
@gggssepgf 你正在翻译哪个项目？
