### ISSUE TITLE
老版PJADV文本提取失败——プリンセスうぃっちぃず

### ISSUE THREAD

**Issue by Sylph1e** [ZQF-ReVN/RxPJADV#4]
大佬您好，我下载了您的PJADV工具，并使用该工具成功提取了闪耀十字军的文本【工具本身能够使用】
![QQ20240831-190216](https://github.com/user-attachments/assets/41560f99-8a5f-4dd6-a0ba-74dcc98a2159)
但在プリンセスうぃっちぃず游戏的提取时，scenario.dat会卡住，出现循环运行爆内存的问题，直到c盘占满后报错退出。
【ScenarioDat_Test.exe测试发生同样的问题，还没有仔细分析是哪出了问题】

プリンセスうぃっちぃず游戏解包出来的文件如下：
![QQ20240831-193612](https://github.com/user-attachments/assets/576d323a-c957-4f95-b79b-894011f19976)
textdata.dat用您的工具TextDataDat_Test.exe，测试可以读取，经观察也与textdata.bin封包格式没有区别。

改用[FuckGalEngine](https://github.com/Inori/FuckGalEngine)的项目，也是读取文件中的数据块，判断接下来要提取的是什么类型的偏移量。但是重新写回去之后，出现如下问题：
①op播放后闪退报错【可以按住ctrl通过op】
②战斗系统启动失效【教程中战斗相关图像没有绘制出来，继续运行会闪退报错；其他战斗会跳过，直接判定胜利】
![805AFDC874985AC292A677F5BED7EF61](https://github.com/user-attachments/assets/b7bffd7e-3967-4cc6-9ffb-a5d84e052d1a)
![DCDC5F829BADD4E7439739AD8AC8F084](https://github.com/user-attachments/assets/a57df6f5-2232-40a7-b672-6661dea54cac)

想咨询一下大佬，当前工具提取プリンセスうぃっちぃず文本是哪出问题了，以及debug应该从什么方面入手，谢谢~

**Comment by Dir-A** [comment]
已修复，该仓库已转为面向开发者，请从新仓库地址下载 https://github.com/Dir-A/ReVN/releases/tag/stable

**Comment by Sylph1e** [comment]
> 已修复，该仓库已转为面向开发者，请从新仓库地址下载 https://github.com/Dir-A/ReVN/releases/tag/stable
真的非常感谢，工具很好用，以上问题已全部解决！

不过这个工具提取文本的时候，选项部分的日文文本并没有被提取出来，选项文本无法修改，显示为乱码。
如果方便的话，麻烦大佬帮忙再改进下工具，谢谢~

另外，该作backlog里人名两边的【】符号是日文编码的，应该是脚本里写入的。
如果方便的话，也麻烦大佬告知下如何对这部分进行修改。
![A97B4FDE6CAF42AD06A8FB89FC35B157](https://github.com/user-attachments/assets/086a2676-d760-4974-99ab-9191814d8832)

**Comment by Sylph1e** [comment]
> 已修复，该仓库已转为面向开发者，请从新仓库地址下载 https://github.com/Dir-A/ReVN/releases/tag/stable

真的非常感谢，工具很好用，以上问题已全部解决！

不过这个工具提取文本的时候，选项部分的日文文本并没有被提取出来，选项文本无法修改，显示为乱码。
如果方便的话，麻烦大佬帮忙再改进下工具，谢谢~

另外，该作backlog里人名两边的【】符号是日文编码的，应该是脚本里写入的。
如果方便的话，也麻烦大佬告知下如何对这部分进行修改。
![QQ20240904-193005](https://github.com/user-attachments/assets/b3c4eb57-3a10-48b2-a737-ee045b8c53e4)

**Comment by Dir-A** [comment]
### 选项
修了，重新下。

### 括号
把push 7981改成push BEA1     `【`  SJIS 0x8179 | GBK 0xA1BE
把push 7A81改成push BFA1    `】`  SJIS 0x817A | GBK 0xA1BF
```
004590FA  prich_ex_crack.exe push 7981
0045911F  prich_ex_crack.exe push 7981
00459375  prich_ex_crack.exe push 7A81
0045939A  prich_ex_crack.exe push 7A81
```

**Comment by Sylph1e** [comment]
> ### 选项
> 修了，重新下。
> 
> ### 括号
> 把push 7981改成push BEA1 `【` SJIS 0x8179 | GBK 0xA1BE 把push 7A81改成push BFA1 `】` SJIS 0x817A | GBK 0xA1BF
> 
> ```
> 004590FA  prich_ex_crack.exe push 7981
> 0045911F  prich_ex_crack.exe push 7981
> 00459375  prich_ex_crack.exe push 7A81
> 0045939A  prich_ex_crack.exe push 7A81
> ```

非常感谢，目前选项已经可以正常提取，不需要用0补位替换原文了！

感谢大佬的解答，如果可以的话，我可以最后咨询一个可能也很基础的问题吗。

不转区打开原始exe，save/load界面能正常打开；
把CreateFontIndirect的charset修改为0x86之后，程序不转区运行时打开save/load会直接崩溃；
搜索0x9F修改了校验范围【三个0x9F改为0xFE】，转区运行，save/load可以打开，日期和难度为SJIS用GBK编码显示的乱码。
这是什么原因，可以修改吗？
![QQ20240905-205102](https://github.com/user-attachments/assets/5753f274-9b0f-4064-8489-58ffc3610149)

**Comment by Dir-A** [comment]
### 崩溃
**主要原因**：是游戏程序自己的bug，它在获取双字节的字符图形数据的分支判断错了GetGlyphOutlineA的返回值，导致new了0xFFFFFFFF个字节的空间，但它这个版本的C++不支持异常处理或使用了不抛出异常的new，导致new失败后返回了0x0地址，这个地址会传递给GetGlyphOutlineA用来写入图形数据，但GetGlyphOutlineA判断传入的地址为0x00不会写入，正常逻辑下，这时候已经获取了图形数据，会对图形数据进行一个灰阶转换，这时候就需要遍历刚刚new出来的空间，但这个空间的地址是0x00，访问即触发异常，最终导致游戏退出。
**次要原因**：由于有编码范围的限制，以及正常情况下引擎只在SJIS环境下运行，所以一般不会导致GetGlyphOutlineA的返回值为0xFFFFFFFF，但修改了charset后，相当于修改了GDI的字体描述信息，导致GetGlyphOutlineA从一个没有对应码点的字体描述信息中去查找对应的图形数据，最终使得GetGlyphOutlineA返回0xFFFFFFFF。
**解决**：把传入CreateFontIndirectA的字体名也改成支持中文显示的字体，比如SimHei就可以基本解决，因为GBK的范围一般都大于SHIFT-JIS的范围，理论上不会导致GetGlyphOutlineA返回值出现问题，但主要可能还是和字体有关。但本质来说就是它引擎程序自己的bug，要彻底解决就要去改那个判断返回值的汇编代码。
![QQ20240905-223229](https://github.com/user-attachments/assets/5471e62f-a66a-463a-a9e0-4017726bfee8)

### 日期
日期在exe中
```
0047D048 -> 年 月 日 日目 ／ ： 時 分 秒 午前 午後 ＡＭ ＰＭ 火 水 木 金 土 曜 早朝 昼 夕方 深夜 
```

### 难度
难度在textdata.dat中，已增加了提取的代码，重新下载最新版本就可以提取出来。

**Comment by Sylph1e** [comment]
感谢大佬！讲解的非常详细！

 ### 工具发现的新bug
在使用的过程中，我发现这个工具还有一个问题，这游戏有些对话是是分段的，就是点击之后，才会弹出对话的后半段。
然而用该工具提取的时候，只会提出前半段，导致出现显示为 xxx（中文）后面跟一堆乱码的文本。
下图为和以前自己提的文本的对比，大佬帮忙看一下，是不是工具还有什么问题呢
![24_9_5_1](https://github.com/user-attachments/assets/0862d76e-efa0-4a4d-9f75-8ac6c0ef2807)
![24_9_5_2](https://github.com/user-attachments/assets/51b04d1e-be51-48fa-ab65-3170c4368fdb)

**Comment by Dir-A** [comment]
修了，重下

**Comment by Sylph1e** [comment]
> 修了，重下

### 崩溃问题已解决
其实之前就nop掉了字体读取的函数，只是没把所有字体都换成SimHei。全部改掉之后，不转区可以打开save/load了。

### 工具正常使用
更新后的工具，使用过程中没有再发现什么问题了，真的感谢大佬！

### 日期修改问题
日期把有显示的文本——年、月、日、上下午、时、分、秒，替换为了GBK编码的十六进制值，能够正常显示。
但数字的部分怎么修改，目前还没有头绪，可以请大佬再帮忙看看吗
![24_9_6_1](https://github.com/user-attachments/assets/20d61f57-88fb-47e7-90bf-6178551e37cc)
![24_9_6_2](https://github.com/user-attachments/assets/4d430cfc-240a-4c83-b132-c79eea4b8aa2)

**Comment by Dir-A** [comment]
改成GBK
```
00483500 -> ０１２３４５６７８９－
```

**Comment by Sylph1e** [comment]
> 改成GBK
> 
> ```
> 00483500 -> ０１２３４５６７８９－
> ```

啊啊，感谢，我傻了，早上搜的时候搜成半角了，还以为搜不到呢
已经可以正常显示了，谢谢大佬~
